---
title: "Project Phase 1"
output: word_document
---

# Project Phase 1
## Olivia Fowler

```{r}
library(ggplot2)
library(lubridate)
library(zoo)
library(dplyr)
library(knitr)
library(tidyverse)
```

```{r}
chicago <- read_csv("~/Spring 2020/BAN 502/Project/chicago.csv")
```


```{r}
chicago=chicago%>%mutate(Date = mdy_hms(Date))
chicago = chicago %>% mutate(Hour = hour(Date)) #creates new variable in dataset with the
summary(chicago$Hour) #shows summary of this new variable
chicago = chicago %>% dplyr::select (Date, Hour, Block, IUCR, "Primary Type", Description, Arrest, Domestic, Beat, District, Ward, "Community Area", "FBI Code", "Location Description",Year, Latitude, Longitude)
chicago = chicago %>% mutate(Arrest = as.factor(Arrest)) %>%
  mutate(Arrest = fct_recode(Arrest, "False" = "No", "True" = "Yes" )) %>%
  mutate(Hour = as.factor(Hour)) %>% mutate('Primary Type' = as_factor(as.character('Primary Type')))%>%
  mutate(Description = as.factor(Description))%>%mutate('Location Description' = as_factor(as.character('Location Description'))) %>%
  mutate(Domestic = as.factor(Domestic))%>%
  mutate(District = as.factor(District))%>%
  mutate(Year = as.factor(Year))%>%
  mutate(Ward = as.factor(Ward))%>%mutate('Community Area' = as_factor(as.character('Community Area')))%>%mutate(Block = as.factor(Block))%>%mutate(IUCR = as.factor(IUCR))
str(chicago)
```

```{r}
chicago$day <- as.factor(wday(chicago$Date))
chicago$month <- as.factor(month(chicago$Date))
```


```{r}
library(tidytext)
library(ggplot2)
library(tidyr)
library(corrplot)
library(GGally)
library(ggcorrplot)
```

```{r}
hist(chicago$Date, breaks=100)
```


```{r}
table(chicago$month)
```


```{r}
table(chicago$Description)[which.max(table(chicago$Description))]
```

```{r}
table(chicago$Description)[which.min(table(chicago$Description))]
```


```{r}
Days <- table(chicago$day)
```

```{r}
barplot(Days)
```

```{r}
table(chicago$"FBI Code")
```

```{r}
table(chicago$"Location Description")
```
```{r}
topcrime = chicago %>%
  group_by(Description) %>%
  summarise(total = n ()) %>%
  distinct() %>%
  top_n(10)
```
```{r}
topcrime %>%
  ggplot(aes(reorder(Description, total), y=total)) +
  geom_col(fill = "green") +
  coord_flip() +
  labs(title = "Chicago Top 10 Crimes in 2018",
       x= "Crime Description",
       y= "Total")
```

```{r}
topblock = chicago %>%
  group_by(Block) %>%
  summarise(total = n ()) %>%
  distinct() %>%
  top_n(10)
```

```{r}
topblock %>%
  ggplot(aes(reorder(Block, total), y=total)) +
  geom_col(fill = "red") +
  coord_flip() +
  labs(title = "Chicago Top 10 Blocks for Crime in 2018",
       x= "Block",
       y= "Total")
```

```{r}
topday = chicago %>%
  group_by(day) %>%
  summarise(total = n ()) %>%
  distinct() %>%
  top_n(7)
```

```{r}
topday %>%
  ggplot(aes(reorder(day, total), y=total)) +
  geom_col(fill = "blue") +
  coord_flip() +
  labs(title = "Chicago Top Days for Crime in 2018",
       x= "Days",
       y= "Total")
```

```{r}
topDistrict = chicago %>%
  group_by(District) %>%
  summarise(total = n ()) %>%
  distinct() %>%
  top_n(10)
```

```{r}
topDistrict %>%
  ggplot(aes(reorder(District, total), y=total)) +
  geom_col(fill = "purple") +
  coord_flip() +
  labs(title = "Chicago Top Districts for Crime in 2018",
       x= "District",
       y= "Total")
```

